# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GameTicTacToe.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import sys
import random


class Ui_MainWindow(QtWidgets.QMainWindow):
    userChoice,cpuChoice = '',''
    gameGrid = None

    def setupUi(self, MainWindow):
        
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(916, 725)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(150, 180, 371, 361))
        self.label.setStyleSheet("background-color: rgb(198, 211, 255);")
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("C:/Users/asus/Pictures/imgs/tictactoe-Grid.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(150, 180, 111, 111))
        self.pushButton.setStyleSheet("background-color: rgba(255, 255, 255, 0);font-size:30px")
        self.pushButton.setText("")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(280, 180, 111, 111))
        self.pushButton_2.setStyleSheet("background-color: rgba(255, 255, 255, 0);font-size:30px")
        self.pushButton_2.setText("")
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(410, 180, 111, 111))
        self.pushButton_3.setStyleSheet("background-color: rgba(255, 255, 255, 0);font-size:30px")
        self.pushButton_3.setText("")
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_4.setGeometry(QtCore.QRect(150, 300, 111, 111))
        self.pushButton_4.setStyleSheet("background-color: rgba(255, 255, 255, 0);font-size:30px")
        self.pushButton_4.setText("")
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_5 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_5.setGeometry(QtCore.QRect(280, 300, 111, 111))
        self.pushButton_5.setStyleSheet("background-color: rgba(255, 255, 255, 0);font-size:30px")
        self.pushButton_5.setText("")
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_6 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_6.setGeometry(QtCore.QRect(400, 310, 111, 111))
        self.pushButton_6.setStyleSheet("background-color: rgba(255, 255, 255, 0);font-size:30px")
        self.pushButton_6.setText("")
        self.pushButton_6.setObjectName("pushButton_6")
        self.pushButton_7 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_7.setGeometry(QtCore.QRect(150, 430, 111, 111))
        self.pushButton_7.setStyleSheet("background-color: rgba(255, 255, 255, 0);font-size:30px")
        self.pushButton_7.setText("")
        self.pushButton_7.setObjectName("pushButton_7")
        self.pushButton_8 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_8.setGeometry(QtCore.QRect(280, 430, 111, 111))
        self.pushButton_8.setStyleSheet("background-color: rgba(255, 255, 255, 0);font-size:30px")
        self.pushButton_8.setText("")
        self.pushButton_8.setObjectName("pushButton_8")
        self.pushButton_9 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_9.setGeometry(QtCore.QRect(410, 430, 111, 111))
        self.pushButton_9.setStyleSheet("background-color: rgba(255, 255, 255, 0);font-size:30px")
        self.pushButton_9.setText("")
        self.pushButton_9.setObjectName("pushButton_9")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(30, 0, 681, 81))
        self.label_2.setStyleSheet("font: 28pt \"Matura MT Script Capitals\";\n"
"text-decoration: underline;")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(50, 100, 271, 41))
        self.label_3.setStyleSheet("font: 20pt \"MS Shell Dlg 2\";")
        self.label_3.setObjectName("label_3")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(320, 90, 101, 61))
        self.lineEdit.setStyleSheet("font: 20pt \"MS Shell Dlg 2\";")
        self.lineEdit.setText("")
        self.lineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit.setObjectName("lineEdit")
        self.pushButton_10 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_10.setGeometry(QtCore.QRect(420, 90, 121, 61))
        self.pushButton_10.setStyleSheet("font: 20pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(255, 73, 97);")
        self.pushButton_10.setObjectName("pushButton_10")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(80, 560, 161, 41))
        self.label_4.setStyleSheet("\n"
"font: 26pt \"Lucida Console\";")
        self.label_4.setObjectName("label_4")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_2.setGeometry(QtCore.QRect(240, 560, 421, 51))
        self.lineEdit_2.setStyleSheet("font: 26pt \"MS Shell Dlg 2\";")
        self.lineEdit_2.setObjectName("lineEdit_2")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 916, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_2.setText(_translate("MainWindow", "TIC TAC TOE GAME"))
        self.label_3.setText(_translate("MainWindow", "Enter your Choice:"))
        self.pushButton_10.setText(_translate("MainWindow", "START"))
        self.label_4.setText(_translate("MainWindow", "Winner"))
        self.initEvents()

    def initEvents(self):
        self.gameGrid = [self.pushButton,self.pushButton_2,self.pushButton_3,
                self.pushButton_4,self.pushButton_5,self.pushButton_6,
                self.pushButton_7,self.pushButton_8,self.pushButton_9]
        self.pushButton_10.clicked.connect(self.startGame)
        for btn in self.gameGrid:
            btn.clicked.connect(self.UserMove)

    def startGame(self):
        self.userChoice = self.lineEdit.text()
        if self.userChoice.upper() == 'X':
            self.cpuChoice = '0'
        else:
            self.cpuChoice = 'X'
        self.lineEdit.setReadOnly(True)
    
    def UserMove(self):
        print(self.userChoice)
        btn = self.sender()
        btn.setText(self.userChoice)
        btn.setDisabled(True)
        self.checkWinner(self.userChoice)
        self.cpuMove()

    def cpuMove(self):
        
        emptyButtons = [btn for btn in self.gameGrid if btn.text() == '']
        if emptyButtons:
            btn = random.choice(emptyButtons)
            btn.setText(self.cpuChoice)
            
            btn.setDisabled(True)
            self.checkWinner(self.cpuChoice)

    def checkWinner(self,player):
        winning_combinations = [[self.pushButton,self.pushButton_2,self.pushButton_3],
                                [self.pushButton_4,self.pushButton_5,self.pushButton_6],
                                [self.pushButton_7,self.pushButton_8,self.pushButton_9],
                                [self.pushButton,self.pushButton_5,self.pushButton_9],
                                [self.pushButton_3,self.pushButton_5,self.pushButton_7],
                                [self.pushButton,self.pushButton_4,self.pushButton_7],
                                [self.pushButton_2,self.pushButton_5,self.pushButton_8],
                                [self.pushButton_3,self.pushButton_6,self.pushButton_9] ]

        for combo in winning_combinations:
            combo_match = True
            for btn in combo:
                if btn.text() != player:
                    combo_match = False
                    break
            if combo_match:
                self.lineEdit_2.setText(player + ' '+ 'Wins..!')
                self.disableButtons()
                return 
                

        all_filled = True
        for btn in self.gameGrid:
            if btn.text() == "":
                all_filled = False
                break

        if all_filled:
            self.lineEdit_2.setText("It's a tie!") 
            self.disableButtons()
            return
    def disableButtons(self):
        for btn in self.gameGrid:
            btn.setDisabled(True)                  

            


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())